# Generated by Django 5.0.1 on 2024-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xabar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangilik',
            options={'ordering': ('-id', '-sarlavha')},
        ),
        migrations.AddField(
            model_name='yangilik',
            name='rasm',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
